name: AdvancementsMenu
version: '${project.version}'
main: me.evlad.advancementsmenu.AdvancementsMenu
api-version: 1.18
author: evlad
description: AdvancementsMenu
commands:
  advancements:
    description: Opens Advancements Menu
    usage: /<command>
    permission: advancementsmenu.open
    aliases:
    - succes
    - success
permissions:
  advancementsmenu.open:
    description: Open advancements menu
    default: true
