name: AdvancementsMenu
version: '${project.version}'
main: me.evlad.advancementsmenu.AdvancementsMenu
api-version: 1.18
author: evlad
description: AdvancementsMenu
commands:
  advancements:
    description: Opens Advancements Menu
    usage: /<command>
    permission: advancementsmenu.open
    aliases:
    - succes
    - success
permissions:
  advancementsmenu.*:
    description: Access all commands
    default: op
    children:
      advancementsmenu.open: true
  advancementsmenu.open:
    description: Open advancements menu
    default: true
    children:
      advancementsmenu.open.player: true
  advancementsmenu.open.player:
    description: Open advancements menu for player
    default: op
